---
title: "3. Variablen, Datentypen & Debugging"
---

## Variablen

::: {.callout-note}
### Beispiel

In Abschnitt haben Sie bereits die (quadratische) Flagge des Kantons Zürich mithilfe der Turtle gezeichnet. Ohne Beachtung der Farben könnte der Code dafür wie in Abschnitt aussehen.

```python
# File: ohne_variable.py
import turtle as t
import math

for _ in range(4):
    t.forward(50)
    t.left(90)

t.forward(50)
t.left(135)
t.forward(50 * math.sqrt(2))

t.hideturtle()
t.done()
```

:::{.callout-note}
💡 **Hinweis**: Dieses Skript verwendet grafische Desktop-Bibliotheken (`turtle` / `pygame`). Führen Sie diesen Code in Ihrer lokalen Entwicklungsumgebung (z.B. VS Code) aus.
:::

Angenommen wir wollten die Grösse der Züri-Flagge ändern, dann müssten wir den Wert `50` an genau **drei Stellen** entsprechend anpassen! Dieses Vorgehen ist zum einen mühsam und zum anderen höchst fehleranfällig (es kann sehr gut passieren, dass eine Änderung nicht konsequent an allen Stellen durchgeführt wird).

Viel besser ist es, wenn wir der Seitenlänge des Quadrats einen Namen geben. Genau dies haben wir in Abschnitt getan: Wir haben der Länge den Namen `laenge` gegeben.

```python
# File: mit_variable.py
import turtle as t
import math

# Wir benutzen die Variable 'laenge', um der Länge einen Namen zu geben:
laenge = 50

for _ in range(4):
    t.forward(laenge)
    t.left(90)

t.forward(laenge)
t.left(135)
t.forward(laenge * math.sqrt(2))

t.hideturtle()
t.done()
```

:::{.callout-note}
💡 **Hinweis**: Dieses Skript verwendet grafische Desktop-Bibliotheken (`turtle` / `pygame`). Führen Sie diesen Code in Ihrer lokalen Entwicklungsumgebung (z.B. VS Code) aus.
:::

Der Ausdruck `laenge` ist ein Beispiel einer sogenannten **Variable**.

:::

::: {.callout-note}
### Variable in Python

Eine *Variable* in Python ist im Wesentlichen ein Name, der auf einen im Speicher (des Computers) abgelegten Wert verweist. Mit der Zuweisung

```{pyodide-python}
a = 436 # a verweist auf ein Objekt vom Typ "ganze Zahl" mit dem Wert 436
```

wird veranlasst, dass der Variablenname `a` zu einer Referenz (einem Verweis) auf den Speicherort eines Objekts vom Typ "ganze Zahl" mit dem Wert `436` wird.

:::

Eine Variable wird erstellt, sobald man ihr mit dem Gleichheitszeichen (`=`) ein Objekt zuweist. Das Gleichheitszeichen hat allerdings nicht dieselbe Bedeutung wie in der Mathematik! Vielmehr bedeutet das Gleichheitszeichen in Python: "die linke Seite soll ein Name für das Ding auf der rechten Seite werden":

$ {\text{`a`}} ={\color{red}\underbrace{\color{black}\text{`10+3`}}}$
\tikz[remember picture, overlay]{\draw[-latex,red] ([yshift=0.1em]a.south) to[bend left] ([yshift=-0.3em]b.south);}

Die Erklärung dieser Zeile ist: "Wir werten den Ausdruck `10 + 3` aus und erhalten die Zahl `13`. Diesen Wert (`13`) speichern wir nun in der Variable `a`".

Wir können den Inhalt der Variable `a` nun mit einem `print()`-Befehl auf dem Terminal ausgeben lassen:

```{pyodide-python}
a = 10 + 3
print(a) # gibt 13 aus

a = 25 # der Wert der Variable wird hier neu definiert
print(a) # gibt jetzt 25 und nicht mehr 13 aus
```

Variablen sind kurz gesagt ein Wort, das auf einen veränderbaren (variablen) Wert verweist. Der Variablenname darf dabei (fast) frei gewählt werden, sofern folgende Regeln eingehalten werden:

::: {.callout-note}
### Benennung von Variablen

Bei der Wahl eines Variablennamens gibt es einige Punkte zu beachten:

1. Der Name muss mit einem Buchstaben oder Unterstrich beginnen (e.g. nicht \verb|1meinname|).
2. Der Name darf kein von Python [reserviertes Wort](https://www.programiz.com/python-programming/keyword-list) sein (`for`, `def`, `if`, etc.).
3. Der Name sollte **sinnvoll** und **beschreibend** (deskriptiv) sein. Wenn Sie beispielsweise die Höhe eines Hauses in einer Variable speichern, ist es sinnvoll, diese `h` oder `hoehe` zu nennen und nicht etwa `x`.
4. Variablennamen dürfen nur alphanumerische Symbole (`a` -- `z`, `A` -- `Z`, `0` -- `9`) und Unterstriche enthalten. Insbesondere also weder Leerzeichen noch Umlaute.
5. Da Variablennamen keine Leerzeichen enthalten dürfen, sollten zusammengesetzte Namen mithilfe von Unterstrichen (\lstinline{_}) gebildet werden:
      

```{pyodide-python}
laenge_rechteck = 100
number_of_occupied_squares = 5
```

:::

::: {.callout-warning}
### Wichtiger Hinweis

In der Mathematik bedeutet das Gleichheitszeichen "der rechte Teil der Gleichung ist gleich dem linken". Dies ist in Python nicht so! Hier bedeutet das Gleichheitszeichen: "Werte den rechten Teil aus und **speichere** das Resultat im linken Teil".

:::

::: {.callout-tip}
### Aufgabe

Berechnen Sie die folgenden Ausdrücke in Python und speichern Sie das Resultat jeweils in einer Variable:

| Berechnung | Name der Variable |
| --- | --- |
| $17 - 3 \cdot 8$ | `res_1` |
| $(5-2) \cdot 4 + 1$ | `res_2` |
| $3^6$ | `res_3` |
| $18^{(2+3)}$ | `res_4` |

Geben Sie die Variablen jeweils mit `print()` aus, um die Resultate zu überprüfen.

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
```{pyodide-python}
# File: arithmetic_vars.py
res_1 = 17 - 3 * 8
res_2 = (5 - 2) * 4 + 1
res_3 = 3**6
res_4 = 18 ** (2 + 3)
print(res_1, res_2, res_3, res_4)
```
:::

:::

::: {.callout-tip}
### Aufgabe

Gegeben sind zwei Variablen `x` und `y`. Sie möchten die Werte dieser zwei Variablen austauschen, so dass danach `x` den ursprünglichen Wert von `y` enthält und umgekehrt. Sie experimentieren zunächst mit folgendem Vorgehen:

```{pyodide-python}
# Anfängliche Werte für x und y
x = 5 
y = 11

# Versuch, die Werte von x und y zu tauschen
x = y
y = x
```

Führen Sie das Programm aus und geben Sie die Werte von `x` und `y` auf dem Terminal aus. Funktioniert das Programm wie erwartet? Weshalb (nicht)?

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
`x` und `y` haben nun beide den Wert `11`. Auf Zeile 6 wird der *Wert* von `y` in `x` gespeichert. Ab diesem Moment haben sowohl die Variablen `x` wie `y` denselben Wert `11`.
:::

:::

::: {.callout-tip}
### Aufgabe

Wie könnte der Code aus Abschnitt angepasst werden, sodass der Tausch korrekt vollzogen wird?

Tipp: Verwenden Sie neben `x` und `y` noch eine dritte Variable.

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
Mit einer Hilfsvariable:

```{pyodide-python}
# anfängliche Werte für x und y:
x = 5 
y = 11

# Tausche die Werte, so dass danach x den Wert 11 hat und y den Wert 5:

# Verwende eine weitere Variable, um den anfänglichen Wert von x zu speichern:
temp = x
x = y
y = temp
```
:::

:::

::: {.callout-warning}
### 🏆 Trophy Challenge

In den Variablen `x` und `y` sei jeweils eine ganze Zahl gespeichert. Schreiben Sie ein Programm, welches die Werte von `x` und `y` tauscht, ohne eine weitere "Hilfsvariable" wie in Abschnitt zu verwenden. Testen Sie Ihr Programm mit `x = 99` und `y = 15`.

Tipp: Definieren Sie zuerst `x = x + y`.

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
```{pyodide-python}
# anfängliche Werte für x und y:
x = 99
y = 15

# Tausche die Werte von x und y:
x = x + y
y = x - y
x = x - y
```
:::

:::

## Teilen mit Rest

In diesem Abschnitt werden wir einige Überlegungen anstellen, welche Sie vielleicht an Ihre Zeit in der Primarschule zurückerinnern werden.

::: {.callout-note}
### Beispiel

- Angenommen seit einem gewissen Zeitpunkt seien 23 Tage vergangen. Der Zeitpunkt liegt also 3 ganze Wochen zurück und in der vierten Woche sind bereits 2 Tage vergangen.
      Wir können die Zahl 23 darstellen als $23 = 7\cdot 3 + 2$. Dabei ist $3$ (der Quotient) das Resultat der **ganzzahligen Division** von $23$ (Dividend) geteilt durch $7$ (Divisor). Dabei bleibt ein **Rest** von $2$.
- Bei der ganzzahligen Division $23$ geteilt durch $7$ bestimmen wir also, wie häufig $7$ vollständig (ganz) in  $23$ "passt".
- Nehmen wir weiter an, der Tag 0 sei ein Montag. Dann war auch schon Tag $-7$ ein Montag und ebenso Tag $+7$.
      Offensichtlich entsprechen zwei Tage genau dann demselben Wochentag, wenn ihre Differenz (die Differenz ihrer Nummern) durch 7 teilbar ist^[Mit anderen Worten: Ihre Differenz ist ein ganzzahliges Vielfaches von 7.].
      So sind beispielsweise die Tage 23 und 37 beide Mittwoche.

:::

::: {.callout-note}
### ganzzahlige Division und Modulo-Operation (informell)

Es seien $a$ und $b$ natürliche Zahlen und $b\neq 0$.

- Wir bezeichnen in Python mit \lstinline{a // b} das Resultat der ganzzahligen Division von \lstinline{a} geteilt durch \lstinline{b} (wie oft hat \lstinline{b} ganz in \lstinline{a} Platz).

      Beispiel: `23 // 7` ist `3`.
- Mit `a % b` (sprich: `a` **modulo** `b`) bezeichnen wir den Rest, welcher bei der ganzzahligen Division von \lstinline{a} geteilt durch \lstinline{b} bleibt. Wir nennen `%` die **Modulo-Operation**.

      Beispiel: `23 % 7` ist `2`.

Für mehr Details zur Division mit Rest siehe Abschnitt.

:::

::: {.callout-note}
### Beispiel

Beispiele für die ganzzahlige Division in Python:

```{pyodide-python}
20 // 3 # ist 6
80 // 4 # ist 20
37 // 5 # ist 7
```

:::

::: {.callout-note}
### Beispiel

Beispiele für Modulo-Berechnungen (Rest der ganzzahligen Division) in Python:

```{pyodide-python}
8 % 3 # ist 2
8 % 4 # ist 0
9 % 5 # ist 4
5 % 9 # ist 5
```

:::

::: {.callout-tip}
### Aufgabe

Füllen Sie die zweite Spalte **von Hand aus**, berechnen Sie danach (zur Kontrolle) die Werte in Python.

| **Code** | **Resultat** |
| --- | --- |
| `1 % 3` | `?` |
| `2 % 3` | `?` |
| `3 % 3` | `?` |
| `4 % 3` | `?` |
| `5 % 3` | `?` |
| `6 % 3` | `?` |

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
| **Code** | **Resultat** |
| --- | --- |
| `1 % 3` | `1` |
| `2 % 3` | `2` |
| `3 % 3` | `0` |
| `4 % 3` | `1` |
| `5 % 3` | `2` |
| `6 % 3` | `0` |
:::

:::

::: {.callout-tip}
### Aufgabe

Es nehmen $p>3$ Personen an einem Fest teil (wählen Sie eine Zahl für $p$). Für das Fest wurden $m > 20$ viele Muffins gebacken (wählen Sie eine Zahl für $m$). Jede Person soll genau gleich viele, ganze Muffins erhalten. Berechnen Sie, wie viele ganze Muffins jede Person erhält und wie viele Muffins nach dieser gerechten Verteilung auf $p$ Personen noch übrig bleiben werden. Verwenden Sie dazu den Modulo-Operator.

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
```{pyodide-python}
# File: modulo_muffin.py
p = 4  # Beispielwert, Anzahl Personen
m = 33  # Beispielwert, Anzahl Muffins
uebrige_muffins = m % p  # übriggebliebene Muffins
print("Anzahl übriggebliebene Muffins:", uebrige_muffins)
```
:::

:::

::: {.callout-note}
### Beispiel

Offensichtlich ist eine natürliche Zahl $n$ genau dann gerade, wenn die Gleichheit $n \;%\; 2 = 0$ gilt, also $n$ beim Teilen durch 2 den Rest 0 hat.

:::

## Zusammengesetzte Zuweisungsoperatoren

Wir haben bislang schon mehrfach Werte von Variablen verändert. In diesem Abschnitt führen wir einige gebräuchliche Python-Operatoren ein. Betrachten Sie das folgende Programm:

```{pyodide-python}
alter = 10
print(alter) # alter hat den Wert 10
alter = alter + 1 # alter hat neu den Wert 11 
print(alter) # printet 11
alter + 5 # berechnet die Summe alter + 5, Inhalt von alter bleibt unverändert
print(alter) # printet 11
z = alter + 5 # Inhalt von alter bleibt unverändert 
print(alter) # printet 11
alter += 7 # alter hat neu den Wert 18
print(alter) # printet 18
```

Es existiert ein fundamentaler Unterschied zwischen den beiden Ausdrücken `x + 5` (Wert von `x` bleibt unverändert) und `x += 5` beziehungsweise `x = x + 5` (Wert von `x` wird überschrieben). Anstelle von `x = x + y` werden wir häufig den zusammengesetzten Operator `+=` in der Form `x += y` verwenden. Analoge zusammengesetzte Operatoren für weitere mathematische Operatoren sind in Abschnitt aufgeführt.

| **zusammengesetzte Zuweisungsoperation** | **Bedeutung** |
| --- | --- |
| `x += y` | speichere `x + y` in `x` |
| `x -= y` | speichere `x - y` in `x` |
| `x *= y` | speichere `x * y` in `x` |
| `x /= y` | speichere `x / y` in `x` |
| `x //= y` | speichere `x // y` in `x` |
| `x %= y` | speichere `x % y` in `x` |

::: {.callout-tip}
### Aufgabe

Zeichnen Sie eine Spirale der Form:

Die kürzeste Seitenlänge der Spirale ist 10 und nach jeder 90-Grad-Rotation soll die Seitenlänge um 10 länger werden.

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
```python
# File: spirale.py
import turtle as t

t.speed(100)

laenge = 10
for _ in range(20):
    t.fd(laenge)
    t.rt(90)
    laenge += 10

t.done()
```

:::{.callout-note}
💡 **Hinweis**: Dieses Skript verwendet grafische Desktop-Bibliotheken (`turtle` / `pygame`). Führen Sie diesen Code in Ihrer lokalen Entwicklungsumgebung (z.B. VS Code) aus.
:::
:::

:::

::: {.callout-tip}
### Aufgabe

Die Kubikzahl einer Zahl $x$ ist gleich der Zahl hoch 3, also $x^3$. Verwenden Sie eine Schleife um die 10 Kubikzahlen $1^3, 2^3, \ldots, 10^3$ auszugeben. Beginnen Sie mit einer Variablen `x = 1` und erhöhen Sie den Wert von `x` in jedem Durchgang der Schleife um 1.

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
```{pyodide-python}
# File: zahlen_kubik.py
x = 1
for _ in range(10):
    print(x**3)
    x += 1
```
:::

:::

::: {.callout-tip}
### Aufgabe

Wandeln Sie das Programm aus \Cref{ex:zahlen_kubik} so ab, dass am Ende zusätzlich die Summe der 10 Kubikzahlen ausgegeben wird. Verwenden Sie dazu eine zweite Variable `summe`, die zu Beginn den Wert 0 hat und in jedem Durchgang der Schleife um die Kubikzahl erhöht wird.

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
```{pyodide-python}
# File: summe_kubik.py
x = 1
summe = 0
for _ in range(10):
    kubik = x**3
    print(kubik)
    summe += kubik
    x += 1

print("Die Summe der ersten 10 Kubikzahlen ist ", summe)
```
:::

:::

## Arbeiten mit Text (Strings)

In Python kann man nicht nur arithmetische Operationen mit Zahlen durchführen, sondern auch mit Text arbeiten. In der Informatik verstehen wir unter einem *Text* jede endliche Folge von Symbolen der Tastatur. Eine solche Folge von Symbolen bezeichnet man auch als *Zeichenkette* (Englisch: *string*). Beispiele von Strings haben wir bereits in Abschnitt gesehen. Wir können Strings, ebenso wie Zahlen, in Variablen speichern.

::: {.callout-note}
### Beispiel

Folgendes Beispiel speichert den Text `"Hello, World`"| in der Variable `a`, der Wert der Variable wird danach auf dem Terminal ausgegeben:

```{pyodide-python}
a = "Hello, World!"
print(a)  # printet den String "Hello, World!" im Terminal 

# anstelle von doppelten Anführungszeichen "..."
# dürfen auch einfache Anführungszeichen '...' verwendet werden:
b = 'Kantonsschule'

# aber auch sowas ist ein String:
c = "23adsf34#     2 @!!30y"

# dies ist der leere String (enthält keine Zeichen und hat die Länge 0):
d = ""
```

:::

### Verkettung und Vervielfachung von Strings

Zeichenketten können verkettet, also aneinandergehängt werden:

```{pyodide-python}
wort = "Kan" + "tons" + "schule"
print(wort) # Kantonsschule
```

Das Zusammenfügen, also die "Addition" von Strings wird *Konkatenation* (Englisch: *concatenation*) genannt.

Strings können mithilfe des \lstinline{*}-Operators vervielfacht werden:

```{pyodide-python}
wort = "abc"
print(4 * wort) # abcabcabcabc
```

Falls Sie also Wiederholungen einer Zeichenkette wünschen, können Sie diese mit einer ganzen Zahl multiplizieren. Diese Zahl bestimmt die Anzahl der Wiederholungen der Zeichenkette. So entspricht der Ausdruck `"a" * 3` beispielsweise dem String `"aaa"`.

::: {.callout-tip}
### Aufgabe

Führen Sie das nachfolgende Programm aus und erklären Sie, was das Programm tut:

```{pyodide-python}
print(" " * 3 + "X" * 1)
print(" " * 2 + "X" * 3)
print(" " * 1 + "X" * 5)
print(" " * 0 + "X" * 7)
print(" " * 3 + "X" * 1)
print(" " * 3 + "X" * 1)
```

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
Das Programm zeichnet einen "Tannenbaum" .
:::

:::

::: {.callout-tip}
### Aufgabe

Erstellen Sie nun ein Programm, das (analog zu Abschnitt) lediglich mit `prints` und Stringoperationen ein "Herz"  zeichnet.

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
```{pyodide-python}
# File: herz.py
print(" " * 2 + "X" * 1 + " " * 4 + "X" * 1 + " " * 1)
print(" " * 1 + "X" * 8 + " " * 1)
print(" " * 2 + "X" * 6 + " " * 1)
print(" " * 3 + "X" * 4 + " " * 2)
print(" " * 4 + "X" * 2 + " " * 2)
```
:::

:::

::: {.callout-warning}
### 🏆 Trophy Challenge

Schreiben Sie ein Programm, welches die Form einer Banane auf dem Terminal ausgibt, indem Sie die Stringoperationen `*` und `+` verwenden.

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
```{pyodide-python}
# File: banana.py
print(" " * 8 + "X" * 4)
print(" " * 7 + "X" * 4)
print(" " * 6 + "X" * 4)
print(" " * 5 + "X" * 5)
print(" " * 4 + "X" * 6)
print(" " * 3 + "X" * 6)
print(" " * 3 + "X" * 6)
print(" " * 3 + "X" * 6)
print(" " * 3 + "X" * 6)
print(" " * 4 + "X" * 6)
print(" " * 5 + "X" * 5)
print(" " * 6 + "X" * 4)
print(" " * 7 + "X" * 4)
print(" " * 9 + "X" * 4)
```
:::

:::

## Datentypen

Bisher haben wir zwei Arten, oder *Typen* von Variablen gesehen: Zahlen und Text (Strings).

```{pyodide-python}
x = 2 + 3 # x ist eine Variable vom Typ "ganze Zahl"
y = "Hallo Welt!" # y ist eine Variable vom Typ "Text"
z = 'Donald Knuth' # ebenfalls eine Variable vom Typ "Text"
```

Variablen vom Typ "Text" werden gut daran erkannt, dass der Wert der Variable (also der Text) in Anführungszeichen steht.

Bei Zahlen gilt es in Python zwischen der Darstellung einer ganzen Zahl (Englisch: *integer number* $\rightarrow$ *int*) und der Darstellung einer Dezimalzahl (Englisch: *floating point number* $\rightarrow$ *float*) zu unterscheiden, siehe Abschnitt. Bitte beachten Sie, dass Dezimalzahlen immer mit Dezimalpunkt und nicht etwa mit einem Komma geschrieben werden, also `2.75` und nicht etwa `2,75`. Kommas werden in Python als Trennzeichen in Auflistungen verwendet.

\begin{table}[H]
\footnotesize
\centering

| **Beispiel** | **Datentyp (englische, Abk.)** | **Datentyp (Deutsch)** |
| --- | --- | --- |
| `"Hallo Welt", 'abc', "42"` | string (str) | Zeichenkette |
| `15, 45, -5, 0` | integer (int) | ganze Zahl |
| `12.23, -5.3346, 23.0` | float (float) | Kommazahl |

\caption{Auswahl elementarer Datentypen in Python und Beispiele}

\end{table}

Folgendes Beispiel illustriert, wie wichtig es ist, sich des Datentyps einer Variable bewusst zu sein. Das Plus-Symbol kann, abhängig vom Kontext, unterschiedliche Bedeutungen haben:

1. Zahlen addieren: `print(2 + 3) # gibt 5 aus`
2. Strings verketten: `print("Hallo" + " " + "Welt") # gibt "Hallo Welt" aus`

Wichtig dabei ist, dass auf beiden Seiten des Plus-Zeichens (`+`) Werte desselben Datentyps stehen, da Python ansonsten nicht weiss, ob es addieren oder verketten soll. Daher ist es in gewissen Fällen nötig, eine Zahl in einen Text umzuwandeln, beispielsweise dann, wenn eine Zahl und ein Text im gleichen Print ausgegeben werden sollen. Hierzu verwenden wir den Befehl `str()`. Beispielsweise gibt uns `str(15)` die Zeichenkette `"15"`.

::: {.callout-note}
### Beispiel
 Führen Sie folgenden Code in VS Code aus und beobachten Sie das Resultat im Terminal:

```{pyodide-python}
n = 20
m = 30
prod = n * m
print(str(n) + " mal " + str(m) + " ist " + str(prod))
```

:::

Eine etwas elegantere Art, Variablen in einem print mit Text zu verbinden ist, die Python-Schreibweise `print(f"...")` zu verwenden. Dabei wird der String mit einem `f` vor den Anführungszeichen eingeleitet. Innerhalb des Strings können Variablen dann in geschweifte Klammern `{...}` gesetzt werden, um deren Wert an dieser Stelle einzufügen. Aufgrund des vorgestellten `f` spricht man hierbei auch von einem *f-String*.

::: {.callout-note}
### Beispiel

Führen Sie folgenden Code in VS Code aus und beobachten Sie das Resultat im Terminal:

```{pyodide-python}
n = 20
m = 30
quot = n / m
print(f"{n} durch {m} ist {quot}")
```

Diese Schreibweise erlaubt es uns, Variablen innerhalb der geschweiften Klammern zu verwenden, ohne sie vorher in Strings umwandeln zu müssen. Wir beobachten allerdings, dass der Quotient nicht sehr schön formatiert wird. Wir können die Anzahl der Dezimalstellen mit der Formatierung `:.2f` anpassen. Dabei bezeichnet `:.2f` eine Dezimalzahl mit 2 Nachkommastellen. Führen Sie folgenden Code aus:

```{pyodide-python}
n = 20
m = 30
quot = n / m
print(f"{n} durch {m} ist {quot:.2f}")
```

Führen Sie dne Code auch aus ohne das kleine `f` vor den Anführungszeichen zu setzen. Sie sollten dabei beobachten, dass der Text `{n} durch {m} ist {quot:.2f}` unverändert ausgegeben wird, da die Variablen nicht ausgewertet werden. Durch das kleine `f` vor den Anführungszeichen wird Python angewiesen, die Variablen innerhalb der geschweiften Klammern auszuwerten und deren Wert an dieser Stelle einzufügen.

:::

::: {.callout-tip}
### Aufgabe

Schreiben Sie ein Python-Programm, welches in einer Schleife die Quotienten $2/3$, $3/3$, $4/3$, etc. bis $11/3$ berechnet und auf dem Terminal ausgibt, z.B.: `"4 durch 3 ist 1.333"`. Verwenden Sie dazu einen `f"`-String und formatieren Sie die Quotienten so, dass jeweils 3 Nachkommastellen angezeigt werden.

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
```{pyodide-python}
n = 2
m = 3

for _ in range(10):
quot = n / m
print(f"{n} durch {m} ist {quot:.3f}")
n += 1
```
:::

:::

::: {.callout-tip}
### Aufgabe

Eine Dame verrät uns die dreistellige Vorwahl $079$ ihrer $10$-stelligen Mobiltelefonnummer. Zudem verrät sie uns auch, dass die letzten drei Ziffern eine gerade Zahl zwischen 0 und 200 darstellen (also einen der Ausdrücke $000, 002, 004, \ldots, 198, 200$).

Schreiben Sie ein Python-Programm, welches alle gemäss obiger Beschreibung möglichen Nummern auflistet.

Die erste Nummer sollte $0790000000$ sein, die letzte $0790000200$.
Das Programm soll die Telefonnummern als Zeichenkette (eine Nummer pro Zeile) ausgeben.

Tipps:

- Mit `str(num)`
      wird aus der Zahl `num` eine Zeichenkette.
- Erinnern Sie sich, was die Operation `+` in dem Ausdruck \lstinline[language=Python,basicstyle=\ttfamily\normalsize]!"In" + "form" + "atik"! macht?
- Abgesehen von der Null selbst, darf eine ganze Zahl in Python nicht mit einer Null beginnen.

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
```{pyodide-python}
# File: telefonnummer.py
num = 790000000
for _ in range(101):
    print("0" + str(num))  # füge die Zeichenkette "0" vorne an
    num += 2
```
:::

:::

::: {.callout-warning}
### Quotienten ganzer Zahlen sind in Python floats

Im Allgemeinen ist der Quotient $n / m$ von zwei ganzen Zahlen $n, m$ keine ganze Zahl. In Python wird deshalb das Resultat einer Division immer als Dezimalzahl (float) angeschaut, auch wenn $n$ durch $m$ ohne Rest teilbar ist^[Das Konzept von *Teilbarkeit* ergibt in den reellen oder rationalen Zahlen keinen Sinn.]:

```{pyodide-python}
bruch = 6 / 2 # bruch ist ein float und kein int
print(bruch) # gibt 3.0 und nicht etwa 3 aus
bruch = int(bruch) # explizite Typenumwandlung von float zu int
print(bruch) # gibt 3 aus

x = 5.999999 
x = int(x) # Weglassen von Dezimalstellen
print(x) # gibt 5 aus
```

Die folgende Schleife erzeugt einen Fehler (`TypeError`):

```{pyodide-python}
# das ist nicht ok:
for _ in range(6 / 2):
print("hallo")

TypeError: 'float' object cannot be interpreted as an integer

# das ist ok:
for _ in range(int(6 / 2)):
print("hallo")
```

da eine Schleife nur "ganzzahlig-viele" Durchgänge durchführen kann, doch `6 / 3` ist `2.0`, also vom Typ float und nicht int.

:::

::: {.callout-warning}
### 🏆 Trophy Challenge

Schreiben Sie ein Programm, welches 123456789 Sekunden in Jahre (à 365 Tage), Tage, Stunden, Minuten und Sekunden umrechnet.
Das Programm soll den folgenden Text ausgeben, wobei alle Zahlen (ausser 123456789) im Programm berechnet werden: 123456789 Sekunden sind 3 Jahre, 333 Tage, 21 Stunden, 33 Minuten, 9 Sekunden!

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
In dem folgenden Programm verwenden wir die Konvention, dass konstante Werte (wie z.B. die Anzahl Sekunden pro Minute) in Grossbuchstaben geschrieben werden:

```{pyodide-python}
# File: s_to_y.py
sekunden_gesamt = 123456789

# Umrechnungsfaktoren
SEK_PRO_MINUTE = 60
SEK_PRO_STUNDE = 60 * SEK_PRO_MINUTE
SEK_PRO_TAG = 24 * SEK_PRO_STUNDE
SEK_PRO_JAHR = 365 * SEK_PRO_TAG

# Jahre berechnen und den Rest behalten
jahre = sekunden_gesamt // SEK_PRO_JAHR
rest = sekunden_gesamt % SEK_PRO_JAHR

# Tage aus dem verbleibenden Rest berechnen
tage = rest // SEK_PRO_TAG
rest = rest % SEK_PRO_TAG

# Stunden aus dem verbleibenden Rest
stunden = rest // SEK_PRO_STUNDE
rest = rest % SEK_PRO_STUNDE

# Minuten und die uebrig bleibenden Sekunden
minuten = rest // SEK_PRO_MINUTE
sekunden = rest % SEK_PRO_MINUTE

print(f"{sekunden_gesamt} Sekunden sind {jahre} Jahre, {tage} Tage, {stunden} Stunden, {minuten} Minuten und {sekunden} Sekunden.")
```
:::

:::

::: {.callout-tip}
### Aufgabe

Mit welchen Datentypen würden Sie folgende Informationen über sich selbst in Python speichern?

- Ihr Vorname
- Ihr Alter in Jahren
- Ihre Grösse in Metern

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen

- Vorname *string*
- Alter in Jahren: *integer*
- Grösse in Metern: *float*

:::

:::

## Textinput

Mithilfe der \lstinline{input}-Funktion kann der User während der Programmausführung zu einer Eingabe aufgefordert werden.

::: {.callout-note}
### Beispiel

Mit der Funktion `input("Hilfstext...")` können wir eine Variable *während* der Programmausführung erstellen:

```{pyodide-python}
""" 
Folgender Befehl druckt den Hilfstext 
'Was ist ihr Name?' auf dem Terminal. 

Die Antwort kann auf dem Terminal eingetippt 
werden und wird danach in der Variable name gespeichert. 

Mit der letzten Zeile wird der eingegebene Name 
danach 5-mal gedruckt.
"""
name = input("Was ist Ihr Name?") 
print(name * 5)
```

Führen Sie diesen Code in VS Code aus und beobachten Sie das Resultat.

:::

::: {.callout-tip}
### Aufgabe

Schreiben Sie ein Programm, das Sie nach Ihrem Namen fragt, indem der Hilfstext `"Wie heissen Sie?"` auf dem Terminal ausgegeben wird. Verwenden Sie dazu die Funktion `name = input("Hilfstext hier...")`. Danach soll Sie das Programm neunmal begrüssen, indem es auf 3 Zeilen je dreimal den Text `Hallo [Ihr Name]` druckt.

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
```{pyodide-python}
name = input("Wie heissen Sie?")

for _ in range(3):
print(("Hallo " + name + " ") * 3)
```
:::

:::

::: {.callout-note}
### Input erwartet immer einen String

Bitte beachten Sie, dass die \lstinline{input("...")}-Funktion in Python den Tastaturinput immer als String auffasst. Falls Ihr Input als Zahl angesehen werden soll, dann müssen Sie den Input `x` mit `int(x)` beziehungsweise `float(x)` konvertieren:

```{pyodide-python}
alter = input("Wie alt bist du?") # alter ist vom Typ 'String'
print("In einem Jahr wirst du", int(alter) + 1, "Jahre alt sein.")
# andere, mögliche Schreibweise mit f"...:
# print(f"In einem Jahr wirst du {int(alter) + 1} Jahre alt sein.")

# dies würde einen Fehler geben, da wir hier die Summe eines Strings (alter)
# und einer ganzen Zahl zu berechnen versuchen:
print("In einem Jahr wirst du", alter + 1, "Jahre alt sein.")
```

:::

## Debugging

Beim Schreiben von Code werden Sie häufig Fehler machen. Der resultierende Code lässt sich nicht ohne Fehlermeldung ausführen oder liefert nicht das gewünschte Resultat. Wir sprechen dabei von *bugs* (englisches Wort für *Käfer*), womit allgemein *Fehler* beziehungsweise unerwünschtes Verhalten oder unerwünschte Resultate gemeint sind. Daher ist es wichtig, zu lernen, wie man einem Problem auf die Schliche kommt. Darum handelt es sich beim sogenannten *debugging* um das Beheben unterschiedlicher Fehlerarten, welche in den folgenden Abschnitten kurz erklärt werden.

### Syntaxfehler

Syntax-Fehler (Englisch: *syntax error*) sind in Programmiersprachen vergleichbar mit Rechtschreibfehlern in Aufsätzen: Es handelt sich um Schreibweisen, die nicht erlaubt sind. Beispielsweise würde folgender Code eine Fehlermeldung geben:

```{pyodide-python}
print "Hello World" # Fehler!
```

Der Fehler tritt aufgrund der Tatsache auf, dass nach dem Befehl `print` Klammern stehen müssen. Der korrekte Code würde wie folgt geschrieben:

```{pyodide-python}
print("Hello World")
```

Syntax-Fehler, also Fehler in der grammatikalischen Struktur einer Programmiersprache, führen dazu, dass der Code nicht richtig ausgeführt werden kann.

Weitere, ähnliche Fehler können etwa auftreten, weil die Klammern nicht geschlossen wurden oder weil die Anführungszeichen bei Texten vergessen wurden:

```{pyodide-python}
print("Hello World" # Syntax-Fehler (Klammer nicht geschlossen)
print(Hello World) # Syntax-Fehler (keine Anführungszeichen)
```

### Laufzeitfehler

Laufzeitfehler (Englisch: *runtime error*) werden erst bei der Ausführung des Programms erkannt. Dabei stimmt zwar die grammatikalische Struktur (Syntax) des Codes, der Code ergibt aber keinen Sinn: Beispielsweise wird versucht, auf Variablen zuzugreifen, welche es gar nicht gibt. Fehler können beispielsweise aufgrund von Gross- und Kleinschreibung auftreten:

```{pyodide-python}
X = 10 + 5
print(x) # Fehler: kleines "x" gibt es nicht!
```

Ein weiterer Laufzeitfehler könnte wie folgt aussehen

```{pyodide-python}
print(Hello, World)
```

In diesem Fall wollte der Autor des Codes den Text `"Hello, World"` auf dem Terminal drucken, hat jedoch die Anführungszeichen vergessen. Dies führt dazu, dass der Code die Variablen `Hello` und `World` drucken will, die es jedoch nicht gibt.

::: {.callout-tip}
### Aufgabe

Führen Sie alle obigen Beispiele in VS Code aus und beobachten Sie die Fehlermeldungen. Verstehen Sie, was mit den Fehlermeldungen gemeint ist?

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
Keine Musterlösung notwendig.
:::

:::

### Semantische Fehler

Semantische Fehler sind Logik-Fehler, also Fehler aufgrund der Tatsache, dass die Programmiererin Denkfehler beim Schreiben gemacht hat. In diesem Fall gibt der Code zwar keine Fehlermeldung aus, die Ausgabe des Codes entspricht jedoch nicht dem erwarteten Resultat. Beispielsweise könnte folgender Code zu einem unerwarteten Resultat führen:

```{pyodide-python}
mittelwert = 3 + 13 / 2
print(mittelwert) # 9.5
```

Das Resultat sollte 8 sein, denn der Mittelwert von 3 und 13 ist $(3 + 13) / 2 = 8$ und nicht etwa $3 + 13 / 2 = 9.5$. Der Fehler hat damit zu tun, dass der Programmierer vergessen hat, Klammern zu setzen. Korrekt wäre folgendes Beispiel:

```{pyodide-python}
mittelwert = (3 + 13) / 2
print(mittelwert) # 8
```

### Debugging-Strategien

Einige Strategien, um fehlerhaften Code zu beheben, sind:

1. Lesen Sie Fehlermeldungen aufmerksam und versuchen Sie diese zu verstehen. Auch die Zeilenangaben in den Fehlermeldungen sind dabei sehr hilfreich.
2. Brechen Sie ihren Code in einzelne Teile auf. Geben Sie Zwischenresultate auf dem Terminal aus, indem Sie `print`-Befehle verwenden.
3. Rechnen Sie einige Beispiele von Hand aus, sofern der Code etwas Komplexeres berechnet.
4. Testen Sie Ihren Code mit (extremen oder besonderen) Testfällen (e.g. negative Zahlen, der Null, dem leeren String).

::: {.callout-tip}
### Aufgabe

Um welche Art von Fehler handelt es sich im Code aus Abschnitt?

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
Dies ist ein Beispiel eines semantischen Fehlers (Fehler in der Logik).
:::

:::

## Weitere Aufgaben

::: {.callout-warning}
### 🏆 Trophy Challenge

Berechnen Sie die ersten 8 Zahlen der Fibonacci-Folge, welche wie folgt aussieht:

$$

0, 1, 1, 2, 3, 5, 8, 13, 21, \ldots

$$

Dabei ist jede Zahl die Summe ihrer beiden Vorgänger in der Folge. Die ersten zwei Glieder 0 und 1 der Folge sind vorgegeben.

Verwenden Sie zur Berechnung der Fibonacci-Zahlen eine `for`-Schleife sowie drei Variablen.

Zeichnen Sie danach mit der Turtle eine Spirale, bestehend aus 8 Viertelkreisen^[Natürlich zeichnen wir hier regelmässige Polygone und keine echten Viertelkreise.], welche als Radius jeweils das **Zehnfache** der zuletzt berechneten Fibonacci-Zahl $1, 2, 3, 5, 8, 13, \ldots$ haben.

Die Spirale sollte folgendermassen aussehen:

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
Diese Musterlösung finden Sie in Abschnitt.
:::

:::

::: {.callout-warning}
### 🏆 Trophy Challenge

Das Programm unten zeigt einen Farbverlauf. Versuchen Sie nachzuvollziehen, wie das Programm funktioniert, und ändern Sie es so ab, dass zwei Kreise mit einem Farbverlauf entstehen, einmal von Rot nach Blau und einmal von Schwarz nach Weiss.

```python
# File: farbverlauf_vorlage.py
﻿import turtle as t

# der folgende Befehl sorgt dafür,
# dass die RGB Werte von 0 bis 255 angegeben werden können
# anstatt von 0 bis 1
t.colormode(255)

# Anfangsfarbe grün
r = 0
g = 255
b = 0

# Es sollen 50 Punkte gezeichnet werden, die immer kleiner werden
# der Durchmesser des ersten Punktes soll 500 sein
durchmesser = 500

for _ in range(50):
    t.pencolor(r, g, b)
    t.dot(durchmesser)
    durchmesser -= 10
    g -= 5

t.done()
```

:::{.callout-note}
💡 **Hinweis**: Dieses Skript verwendet grafische Desktop-Bibliotheken (`turtle` / `pygame`). Führen Sie diesen Code in Ihrer lokalen Entwicklungsumgebung (z.B. VS Code) aus.
:::

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
Diese Musterlösung finden Sie in Abschnitt.
:::

:::

::: {.callout-warning}
### 🏆 Trophy Challenge

Das Programm unten kann eine Dezimalzahl, die kleiner als 1024 ist, in eine Binärzahl umwandeln. Ändern Sie das Programm so ab, dass es folgende Anforderungen erfüllt:

- Der Benutzer soll die Dezimalzahl eingeben können (verwenden Sie dazu die `input`-Funktion).
- Das Programm soll auch für Dezimalzahlen funktionieren, die im Binärsystem 16 Stellen benötigen (also Dezimalzahlen bis 65535).
- Das Programm soll die Binärzahl als String ausgeben (also z.B. `"0000000000001010"` für die Dezimalzahl 10).

```{pyodide-python}
# File: dez_zu_bin_vorlage.py
﻿"""
Dieses Programm wandelt Dezimalzahlen in Binärzahlen um.
Die eingegebene Dezimalzahl muss kleiner als 1023 sein.
"""

# Die folgende Dezimalzahl soll umgewandelt werden
zahl = 892

# Beginnen mit der groessten Basisgroesse
# In diesem Programm ist es  2^9 = 512
basisgroesse = 2**9

# Berechunng der 10 Ziffern der Binärzahl
for _ in range(10):
    # Ziffer: Wie häufig passt die Basisgrösse in den Betrag?
    ziffer = zahl // basisgroesse
    print(ziffer, "ist die ", basisgroesse, "er Ziffer")

    #  Welche Zahl muss durch die weiteren Basisgrössen abgedeckt werden?
    zahl -= ziffer * basisgroesse

    # Basisgrösse wird auf die nächst kleinere Basisgrösse gesetzt.
    basisgroesse //= 2
```

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
Diese Musterlösung finden Sie in Abschnitt.
:::

:::

%

## Längere Lösungen

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
[mychallenge:fibonacci_spirale]

```python
# File: challenge_fib.py
import math
import turtle as t

t.speed(10000)

# Anzahl zu zeichnender "Viertelkreis"
anzahl_halbkreise = 8

# wir stellen einen Viertelkreis durch einen Viertel
# eines Vielecks dar (je mehr Ecken desto genauer)
anzahl_ecken_viertel = 40

# Startwerte der Fibonacci-Folge
f_0 = 0
f_1 = 1

for _ in range(anzahl_halbkreise):
    # f_2 ist die nächste Zahl der Fibonacci-Folge
    f_2 = f_0 + f_1

    # Kreis
    radius = f_2 * 10
    umfang = 2 * radius * math.pi

    # Kantenlänge des Vielecks
    kantenlaenge_vieleck = umfang / (4 * anzahl_ecken_viertel)

    for _ in range(anzahl_ecken_viertel):
        t.fd(kantenlaenge_vieleck)

        """
        nach einem Viertelkreis haben wir uns um 90 Grad gedreht
        an jeder Ecke müssen wir deshalb um
        90 Grad / anzahl_ecken_viertel drehen
        """

        t.rt(90 / anzahl_ecken_viertel)

    # Update der Vorgänger
    f_0 = f_1
    f_1 = f_2

t.done()
```

:::{.callout-note}
💡 **Hinweis**: Dieses Skript verwendet grafische Desktop-Bibliotheken (`turtle` / `pygame`). Führen Sie diesen Code in Ihrer lokalen Entwicklungsumgebung (z.B. VS Code) aus.
:::
:::

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
[mychallenge:farbverlauf]

```python
# File: farbverlauf.py
﻿import turtle as t

# der folgende Befehl sorgt dafür,
# dass die RGB Werte von 0 bis 255 angegeben werden können
# anstatt von 0 bis 1
t.colormode(255)

# setze die Turtle etwas nach links
t.teleport(-250, 0)

# Anfangsfarbe grün
r = 255
g = 0
b = 0

# Es sollen 50 Punkte gezeichnet werden, die immer kleiner werden
# der Durchmesser des ersten Punktes soll 500 sein
durchmesser = 500

for _ in range(50):
    t.pencolor(r, g, b)
    t.dot(durchmesser)
    durchmesser -= 10
    r -= 5
    b += 5

# setze die Turtle etwas nach rechts
t.teleport(250, 0)

# Anfangsfarbe grün
r = 0
g = 0
b = 0

# Es sollen 50 Punkte gezeichnet werden, die immer kleiner werden
# der Durchmesser des ersten Punktes soll 500 sein
durchmesser = 500

for _ in range(50):
    t.pencolor(r, g, b)
    t.dot(durchmesser)
    durchmesser -= 10
    r += 5
    b += 5
    g += 5

t.done()
```

:::{.callout-note}
💡 **Hinweis**: Dieses Skript verwendet grafische Desktop-Bibliotheken (`turtle` / `pygame`). Führen Sie diesen Code in Ihrer lokalen Entwicklungsumgebung (z.B. VS Code) aus.
:::
:::

::: {.callout-caution collapse="true"}
### 💡 Musterlösung anzeigen
[mychallenge:dez_zu_bin]

```{pyodide-python}
# File: dez_zu_bin.py
﻿"""
Dieses Programm wandelt Dezimalzahlen in Binärzahlen um
Die eingegebene Dezimalzahl muss kleiner als 1024 sein.
"""

# die folgende Dezimalzahl soll umgewandelt werden
zahl = int(input("Welche Zahl soll umgewandelt werden? "))

# Beginnen mit der groessten Basisgroesse
# für 16 Bit Zahlen ist dies 65535
basisgroesse = 2**15

binaerzahl = ""

# Berechnung der 10 Ziffern der Binärzahl
for _ in range(16):
    # Ziffer: Wie häufig passt die Basisgrösse in den Betrag?
    ziffer = zahl // basisgroesse

    # die Ziffer wird in einen String umgewandelt und an die Binärzahl angehängt
    binaerzahl += str(ziffer)

    #  Welche Zahl muss durch die weiteren Basisgrössen abgedeckt werden?
    zahl -= ziffer * basisgroesse

    # Basisgrösse wird auf die nächst kleinere Basisgrösse gesetzt.
    basisgroesse //= 2

# Ausgabe der Binärzahl
print(f"Die binäre Darstellung der eingegebenen Zahl ist: {binaerzahl}")
```
:::

}
